#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
env_file="$script_dir/.env"

secret() { openssl rand -hex 32; }

if [[ ! -f "$env_file" ]]; then
  umask 077
  {
    printf 'NEXTAUTH_SECRET=%s\n' "$(secret)"
    printf 'SALT=%s\n' "$(secret)"
    printf 'ENCRYPTION_KEY=%s\n' "$(secret)"
    printf 'POSTGRES_PASSWORD=%s\n' "$(secret)"
    printf 'CLICKHOUSE_PASSWORD=%s\n' "$(secret)"
    printf 'REDIS_AUTH=%s\n' "$(secret)"
    printf 'MINIO_ROOT_PASSWORD=%s\n' "$(secret)"
  } > "$env_file"
  printf 'Created local secrets at %s\n' "$env_file"
fi

if ! grep -q '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file"; then
  umask 077
  {
    printf 'LANGFUSE_INIT_ORG_ID=emberhold-local\n'
    printf 'LANGFUSE_INIT_ORG_NAME=Emberhold Local\n'
    printf 'LANGFUSE_INIT_PROJECT_ID=emberhold-supervisor\n'
    printf 'LANGFUSE_INIT_PROJECT_NAME=Emberhold Supervisor\n'
    printf 'LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-local-%s\n' "$(secret)"
    printf 'LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-local-%s\n' "$(secret)"
    printf 'LANGFUSE_INIT_USER_EMAIL=local@emberhold.invalid\n'
    printf 'LANGFUSE_INIT_USER_NAME=Local Operator\n'
    printf 'LANGFUSE_INIT_USER_PASSWORD=%s\n' "$(secret)"
  } >> "$env_file"
  printf 'Created the local Emberhold Supervisor project credentials.\n'
fi

supervisor_env="$script_dir/../.env"
if [[ ! -f "$supervisor_env" ]]; then
  umask 077
  : > "$supervisor_env"
fi
if ! grep -q '^LANGFUSE_PUBLIC_KEY=' "$supervisor_env"; then
  {
    printf '\n# Local Langfuse telemetry. Generated by observability/setup-local.sh.\n'
    printf 'SUPERVISOR_OBSERVABILITY_ENABLED=true\n'
    printf 'SUPERVISOR_OBSERVABILITY_ENVIRONMENT=local\n'
    printf 'LANGFUSE_BASE_URL=http://127.0.0.1:3001\n'
    grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=/LANGFUSE_PUBLIC_KEY=/'
    grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_SECRET_KEY=/LANGFUSE_SECRET_KEY=/'
  } >> "$supervisor_env"
  printf 'Enabled local supervisor telemetry in %s\n' "$supervisor_env"
fi

docker compose --env-file "$env_file" -f "$script_dir/docker-compose.yml" up -d
printf 'Langfuse is starting at http://127.0.0.1:3001\n'
printf 'The local Emberhold Supervisor project is ready. Run emberhold-observability-import to backfill SQLite history.\n'
