#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
env_file="$script_dir/.env"
shared_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/runbook-supervisor"
shared_config_file="$shared_config_dir/langfuse.env"

secret() { openssl rand -hex 32; }

write_shared_project_config() {
  [[ -f "$env_file" ]] || return 0
  grep -q '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file" || return 0
  umask 077
  mkdir -p "$shared_config_dir"
  {
    printf '# Shared local Langfuse default project. Generated by setup-local.sh.\n'
    printf 'LANGFUSE_BASE_URL=http://127.0.0.1:3001\n'
    grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=/LANGFUSE_PUBLIC_KEY=/'
    grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_SECRET_KEY=/LANGFUSE_SECRET_KEY=/'
  } > "$shared_config_file"
  chmod 600 "$shared_config_file"
  printf 'Registered shared Langfuse project credentials at %s\n' "$shared_config_file"
}

usage() {
  cat <<'EOF'
Usage: ./setup-local.sh [options]

Create or start the one shared local Langfuse service.

Options apply only when bootstrapping a brand-new Langfuse instance:
  --email EMAIL       Initial administrator email (default: local@supervisor.invalid)
  --name NAME         Initial administrator display name (default: Local Operator)
  --password PASSWORD Initial administrator password (default: securely generated)
  -h, --help          Show this help.

Environment alternatives: LANGFUSE_SETUP_EMAIL, LANGFUSE_SETUP_NAME, and
LANGFUSE_SETUP_PASSWORD. Existing Langfuse accounts are never overwritten.
EOF
}

bootstrap_email="${LANGFUSE_SETUP_EMAIL:-local@supervisor.invalid}"
bootstrap_name="${LANGFUSE_SETUP_NAME:-Local Operator}"
bootstrap_password="${LANGFUSE_SETUP_PASSWORD:-}"
account_options=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --email)
      [[ $# -ge 2 ]] || { printf '%s\n' '--email requires a value.' >&2; exit 2; }
      bootstrap_email="$2"; account_options=true; shift 2 ;;
    --name)
      [[ $# -ge 2 ]] || { printf '%s\n' '--name requires a value.' >&2; exit 2; }
      bootstrap_name="$2"; account_options=true; shift 2 ;;
    --password)
      [[ $# -ge 2 ]] || { printf '%s\n' '--password requires a value.' >&2; exit 2; }
      bootstrap_password="$2"; account_options=true; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

for value in "$bootstrap_email" "$bootstrap_name" "$bootstrap_password"; do
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { printf '%s\n' 'Bootstrap account values cannot contain newlines.' >&2; exit 2; }
done

# Langfuse is a machine-wide shared service. A project clone must never create
# another local stack just because its own observability/.env is absent.
if curl --fail --silent --show-error --max-time 2 http://127.0.0.1:3001/ >/dev/null 2>&1; then
  if [[ "$account_options" == true ]]; then
    printf '%s\n' 'A shared Langfuse instance is already running; account options were not applied.' >&2
    printf '%s\n' 'Existing accounts are preserved. Change them in Langfuse instead.' >&2
    exit 2
  fi
  write_shared_project_config
  printf 'A shared local Langfuse instance is already running at http://127.0.0.1:3001; reusing it.\n'
  exit 0
fi

if [[ ! -f "$env_file" ]]; then
  umask 077
  {
    printf 'NEXTAUTH_SECRET=%s\n' "$(secret)"
    printf 'SALT=%s\n' "$(secret)"
    printf 'ENCRYPTION_KEY=%s\n' "$(secret)"
    printf 'POSTGRES_PASSWORD=%s\n' "$(secret)"
    printf 'CLICKHOUSE_PASSWORD=%s\n' "$(secret)"
    printf 'REDIS_AUTH=%s\n' "$(secret)"
    printf 'MINIO_ROOT_PASSWORD=%s\n' "$(secret)"
  } > "$env_file"
  printf 'Created local secrets at %s\n' "$env_file"
fi

if ! grep -q '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file"; then
  [[ -n "$bootstrap_password" ]] || bootstrap_password="$(secret)"
  umask 077
  {
    printf 'LANGFUSE_INIT_ORG_ID=supervisor-local\n'
    printf 'LANGFUSE_INIT_ORG_NAME=Supervisor Local\n'
    printf 'LANGFUSE_INIT_PROJECT_ID=runbook-supervisor\n'
    printf 'LANGFUSE_INIT_PROJECT_NAME=Runbook Supervisor\n'
    printf 'LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-local-%s\n' "$(secret)"
    printf 'LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-local-%s\n' "$(secret)"
    printf 'LANGFUSE_INIT_USER_EMAIL=%s\n' "$bootstrap_email"
    printf 'LANGFUSE_INIT_USER_NAME=%s\n' "$bootstrap_name"
    printf 'LANGFUSE_INIT_USER_PASSWORD=%s\n' "$bootstrap_password"
  } >> "$env_file"
  printf 'Created the local Runbook Supervisor project credentials.\n'
elif [[ "$account_options" == true ]]; then
  printf '%s\n' 'Local Langfuse bootstrap credentials already exist; account options were not applied.' >&2
  printf '%s\n' 'Existing accounts are preserved. Change them in Langfuse instead.' >&2
  exit 2
fi

supervisor_env="$script_dir/../.env"
if [[ ! -f "$supervisor_env" ]]; then
  umask 077
  : > "$supervisor_env"
fi
if ! grep -q '^LANGFUSE_PUBLIC_KEY=' "$supervisor_env"; then
  {
    printf '\n# Local Langfuse telemetry. Generated by observability/setup-local.sh.\n'
    printf 'SUPERVISOR_OBSERVABILITY_ENABLED=true\n'
    printf 'SUPERVISOR_OBSERVABILITY_ENVIRONMENT=local\n'
    printf 'LANGFUSE_BASE_URL=http://127.0.0.1:3001\n'
    grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=/LANGFUSE_PUBLIC_KEY=/'
    grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "$env_file" | sed 's/^LANGFUSE_INIT_PROJECT_SECRET_KEY=/LANGFUSE_SECRET_KEY=/'
  } >> "$supervisor_env"
  printf 'Enabled local supervisor telemetry in %s\n' "$supervisor_env"
fi

docker compose --env-file "$env_file" -f "$script_dir/docker-compose.yml" up -d
write_shared_project_config
printf 'Langfuse is starting at http://127.0.0.1:3001\n'
printf 'The local Runbook Supervisor project is ready. Run supervisor-observability-import to backfill SQLite history.\n'
