"""Interactive project configuration for the reusable supervisor."""

from __future__ import annotations

import argparse
import getpass
import os
import tempfile
from pathlib import Path

from dotenv import dotenv_values


DEFAULTS = {
    # The intended installation is a submodule at the project-root `supervisor`.
    # This resolves to the containing project while still remaining editable.
    "SUPERVISOR_REPO_ROOT": "..",
    # Operational evidence belongs to the controlled project's root, not the
    # reusable submodule. This keeps a supervisor upgrade from owning or
    # obscuring a project's execution history.
    "SUPERVISOR_DATABASE_PATH": "../.state/supervisor.sqlite3",
    "SUPERVISOR_QWEN_ATTEMPTS": "1",
    "SUPERVISOR_OPENHANDS_ATTEMPTS": "1",
    "SUPERVISOR_CODEX_ATTEMPTS": "3",
    "SUPERVISOR_CODEX_FINAL_ATTEMPTS": "3",
    "SUPERVISOR_DASHBOARD_PORT": "8765",
    "SUPERVISOR_WORKER_TIMEOUT_SECONDS": "1800",
    "SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS": "600",
    "SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS": "30",
    "SUPERVISOR_AUTO_COMMIT": "false",
    "SUPERVISOR_AUTO_PUSH": "false",
    "SUPERVISOR_OBSERVABILITY_ENABLED": "false",
    "SUPERVISOR_OBSERVABILITY_ENVIRONMENT": "local",
    "LANGFUSE_BASE_URL": "http://127.0.0.1:3001",
}


def _prompt(label: str, default: str, *, secret: bool = False) -> str:
    prompt = f"{label} [{default}]: " if default else f"{label}: "
    value = getpass.getpass(prompt) if secret else input(prompt)
    return value.strip() or default


def _yes_no(label: str, default: bool) -> bool:
    suffix = "Y/n" if default else "y/N"
    value = input(f"{label} [{suffix}]: ").strip().lower()
    return default if not value else value in {"y", "yes"}


def _value(values: dict[str, str | None], key: str) -> str:
    return str(values.get(key) or os.getenv(key) or DEFAULTS.get(key, ""))


def _write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by `supervisor configure`. Keep this file out of Git.",
        "# Re-run the command whenever the agent, QA, dashboard, or telemetry policy changes.",
        "",
    ]
    for key in sorted(values):
        value = values[key]
        if value:
            lines.append(f"{key}={value}")
    payload = "\n".join(lines) + "\n"
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary.write(payload)
        temporary_path = Path(temporary.name)
    temporary_path.replace(path)
    path.chmod(0o600)


def configure(path: Path) -> None:
    existing = dotenv_values(path) if path.is_file() else {}
    values = {key: str(value) for key, value in existing.items() if value is not None}
    print("Configure the project-local supervisor. Press Enter to keep a shown value.")
    values["SUPERVISOR_REPO_ROOT"] = _prompt("Project repository root", _value(existing, "SUPERVISOR_REPO_ROOT"))
    values["SUPERVISOR_DATABASE_PATH"] = _prompt("SQLite database path", _value(existing, "SUPERVISOR_DATABASE_PATH"))
    values["SUPERVISOR_DASHBOARD_PORT"] = _prompt("Preferred dashboard port (a free port is selected if busy)", _value(existing, "SUPERVISOR_DASHBOARD_PORT"))
    values["SUPERVISOR_WORKER_TIMEOUT_SECONDS"] = _prompt("Worker timeout in seconds", _value(existing, "SUPERVISOR_WORKER_TIMEOUT_SECONDS"))
    values["SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS"] = _prompt("Qwen no-progress timeout in seconds", _value(existing, "SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS"))
    values["SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS"] = _prompt("Terminal heartbeat in seconds", _value(existing, "SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS"))

    print("\nAgent retry policy (total attempts, including the first attempt):")
    for key, label in (
        ("SUPERVISOR_QWEN_ATTEMPTS", "Qwen attempts"),
        ("SUPERVISOR_OPENHANDS_ATTEMPTS", "OpenHands attempts"),
        ("SUPERVISOR_CODEX_ATTEMPTS", "Codex fallback attempts"),
        ("SUPERVISOR_CODEX_FINAL_ATTEMPTS", "Codex final-review attempts"),
    ):
        values[key] = _prompt(label, _value(existing, key))

    values["SUPERVISOR_ALLOW_AUTONOMOUS_WRITES"] = "true" if _yes_no("Allow coding agents to edit this project", _value(existing, "SUPERVISOR_ALLOW_AUTONOMOUS_WRITES") == "true") else "false"
    values["SUPERVISOR_AUTO_COMMIT"] = "true" if _yes_no("Commit accepted tasks automatically", _value(existing, "SUPERVISOR_AUTO_COMMIT") == "true") else "false"
    values["SUPERVISOR_AUTO_PUSH"] = "true" if _yes_no("Push accepted task commits automatically", _value(existing, "SUPERVISOR_AUTO_PUSH") == "true") else "false"

    print("\nOptional agent adapters (leave blank to keep the current value):")
    for key, label in (
        ("QWEN_CODER_COMMAND", "Qwen worker command"),
        ("OPENHANDS_COMMAND", "OpenHands worker command"),
        ("CODEX_COMMAND", "Codex worker command"),
        ("BROWSER_QA_COMMAND", "Browser QA command"),
        ("VISUAL_REVIEW_COMMAND", "Visual review command"),
        ("QWEN_MODEL", "Qwen model"),
        ("LLM_MODEL", "OpenHands model"),
        ("LLM_BASE_URL", "OpenHands/Qwen base URL"),
        ("CODEX_MODEL", "Codex model"),
    ):
        values[key] = _prompt(label, _value(existing, key))

    enabled = _yes_no("Send observability to Langfuse", _value(existing, "SUPERVISOR_OBSERVABILITY_ENABLED") == "true")
    values["SUPERVISOR_OBSERVABILITY_ENABLED"] = "true" if enabled else "false"
    if enabled:
        values["SUPERVISOR_OBSERVABILITY_ENVIRONMENT"] = _prompt("Langfuse environment", _value(existing, "SUPERVISOR_OBSERVABILITY_ENVIRONMENT"))
        values["LANGFUSE_BASE_URL"] = _prompt("Langfuse base URL", _value(existing, "LANGFUSE_BASE_URL"))
        values["LANGFUSE_PUBLIC_KEY"] = _prompt("Langfuse public key", _value(existing, "LANGFUSE_PUBLIC_KEY"), secret=True)
        values["LANGFUSE_SECRET_KEY"] = _prompt("Langfuse secret key", _value(existing, "LANGFUSE_SECRET_KEY"), secret=True)

    _write_env(path, values)
    print(f"Wrote {path} (mode 600). Secrets were not printed.")
    print("Next: run `emberhold-supervisor --task-id <ID>` or `emberhold-dashboard`.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Configure a project-local evidence-gated supervisor.")
    commands = parser.add_subparsers(dest="command", required=True)
    configure_parser = commands.add_parser("configure", help="Interactively create or update an ignored .env configuration file.")
    configure_parser.add_argument("--config", type=Path, default=Path(".env"), help="Configuration file to write (default: .env).")
    arguments = parser.parse_args()
    if arguments.command == "configure":
        configure(arguments.config.expanduser().resolve())


if __name__ == "__main__":
    main()
