"""Interactive project configuration for the reusable supervisor."""

from __future__ import annotations

import argparse
import getpass
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

from dotenv import dotenv_values


DEFAULTS = {
    # The intended installation is a submodule at the project-root `supervisor`.
    # This resolves to the containing project while still remaining editable.
    "SUPERVISOR_REPO_ROOT": "..",
    # Operational evidence belongs to the controlled project's root, not the
    # reusable submodule. This keeps a supervisor upgrade from owning or
    # obscuring a project's execution history.
    "SUPERVISOR_DATABASE_PATH": "../.state/supervisor.sqlite3",
    "SUPERVISOR_QWEN_ATTEMPTS": "1",
    "SUPERVISOR_OPENHANDS_ATTEMPTS": "1",
    "SUPERVISOR_CODEX_ATTEMPTS": "3",
    "SUPERVISOR_CODEX_FINAL_ATTEMPTS": "3",
    "SUPERVISOR_DASHBOARD_PORT": "8765",
    "SUPERVISOR_WORKER_TIMEOUT_SECONDS": "1800",
    "SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS": "600",
    "SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS": "30",
    "SUPERVISOR_AUTO_COMMIT": "false",
    "SUPERVISOR_AUTO_PUSH": "false",
    "SUPERVISOR_OBSERVABILITY_ENABLED": "false",
    "SUPERVISOR_OBSERVABILITY_ENVIRONMENT": "local",
    "LANGFUSE_BASE_URL": "http://127.0.0.1:3001",
    # These bundled adapters are safe defaults: they still need their
    # respective CLI/provider installed, and editing remains disabled until
    # the user explicitly enables SUPERVISOR_ALLOW_AUTONOMOUS_WRITES.
    "QWEN_CODER_COMMAND": "./.venv/bin/python scripts/qwen_worker.py {task_file}",
    "OPENHANDS_COMMAND": "./.venv/bin/python scripts/openhands_worker.py {task_file}",
    "CODEX_COMMAND": "./.venv/bin/python scripts/codex_worker.py {task_file}",
    "BROWSER_QA_COMMAND": "./.venv/bin/python scripts/browser_worker.py {task_file}",
}

DEFAULT_SUPERVISOR_URL = "git@github.com:jakowicz/supervisor.git"
MINIMUM_PYTHON_VERSION = (3, 10)

RUNBOOK_TEMPLATE = """---
task_id: T001
sequence: 1
title: Describe one small, reviewable change
browser_impact: none
playwright_spec:
---

## Objective

Describe the smallest complete outcome. State what is in scope and, equally
important, what must not be changed.

## Acceptance criteria

- The intended behaviour is implemented and documented where it affects users or developers.
- Focused automated tests cover the change and pass.
- No unrelated refactors, network calls, or credentials are introduced.
"""

RUNBOOKS_README = """# Runbooks

Put one Markdown runbook here for each small, independently reviewable task.
Start with `TEMPLATE.md`, assign a unique task ID and sequence, and be precise
about acceptance criteria. Then run it from `../supervisor`:

```zsh
./.venv/bin/supervisor-run --runbook ../runbooks/T001.md
```
"""


def _prompt(label: str, default: str, *, secret: bool = False) -> str:
    prompt = (
        f"{label} (press Enter to keep the current value): "
        if secret and default
        else f"{label} [{default}]: " if default else f"{label}: "
    )
    value = getpass.getpass(prompt) if secret else input(prompt)
    return value.strip() or default


def _yes_no(label: str, default: bool) -> bool:
    suffix = "Y/n" if default else "y/N"
    value = input(f"{label} [{suffix}]: ").strip().lower()
    return default if not value else value in {"y", "yes"}


def _project_path_prompt(default: Path | None = None) -> Path:
    """Prompt for the only required project-init value before other setup."""

    shown_default = str(default) if default else ""
    while True:
        value = _prompt("Project directory", shown_default)
        if value:
            return Path(value).expanduser().resolve()
        print("A project directory is required.")


def _value(values: dict[str, str | None], key: str) -> str:
    return str(values.get(key) or os.getenv(key) or DEFAULTS.get(key, ""))


def _write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by `supervisor configure`. Keep this file out of Git.",
        "# Re-run the command whenever the agent, QA, dashboard, or telemetry policy changes.",
        "",
    ]
    for key in sorted(values):
        value = values[key]
        if value:
            lines.append(f"{key}={value}")
    payload = "\n".join(lines) + "\n"
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary.write(payload)
        temporary_path = Path(temporary.name)
    temporary_path.replace(path)
    path.chmod(0o600)


def configure(path: Path) -> None:
    existing = dotenv_values(path) if path.is_file() else {}
    values = {key: str(value) for key, value in existing.items() if value is not None}
    print("Configure the project-local supervisor. Press Enter to keep a shown value.")
    values["SUPERVISOR_REPO_ROOT"] = _prompt(
        "Application project directory agents may inspect and modify (normally ..)",
        _value(existing, "SUPERVISOR_REPO_ROOT"),
    )
    values["SUPERVISOR_DATABASE_PATH"] = _prompt("SQLite database path", _value(existing, "SUPERVISOR_DATABASE_PATH"))
    values["SUPERVISOR_DASHBOARD_PORT"] = _prompt("Preferred dashboard port (a free port is selected if busy)", _value(existing, "SUPERVISOR_DASHBOARD_PORT"))
    values["SUPERVISOR_WORKER_TIMEOUT_SECONDS"] = _prompt("Worker timeout in seconds", _value(existing, "SUPERVISOR_WORKER_TIMEOUT_SECONDS"))
    values["SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS"] = _prompt("Qwen no-progress timeout in seconds", _value(existing, "SUPERVISOR_QWEN_IDLE_TIMEOUT_SECONDS"))
    values["SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS"] = _prompt("Terminal heartbeat in seconds", _value(existing, "SUPERVISOR_PROGRESS_HEARTBEAT_SECONDS"))

    print("\nAgent retry policy (total attempts, including the first attempt):")
    for key, label in (
        ("SUPERVISOR_QWEN_ATTEMPTS", "Qwen attempts"),
        ("SUPERVISOR_OPENHANDS_ATTEMPTS", "OpenHands attempts"),
        ("SUPERVISOR_CODEX_ATTEMPTS", "Codex fallback attempts"),
        ("SUPERVISOR_CODEX_FINAL_ATTEMPTS", "Codex final-review attempts"),
    ):
        values[key] = _prompt(label, _value(existing, key))

    values["SUPERVISOR_ALLOW_AUTONOMOUS_WRITES"] = "true" if _yes_no("Allow coding agents to edit this project", _value(existing, "SUPERVISOR_ALLOW_AUTONOMOUS_WRITES") == "true") else "false"
    values["SUPERVISOR_AUTO_COMMIT"] = "true" if _yes_no("Commit accepted tasks automatically", _value(existing, "SUPERVISOR_AUTO_COMMIT") == "true") else "false"
    values["SUPERVISOR_AUTO_PUSH"] = "true" if _yes_no("Push accepted task commits automatically", _value(existing, "SUPERVISOR_AUTO_PUSH") == "true") else "false"

    print("\nAgent adapters and models (press Enter to keep each shown value):")
    for key, label in (
        ("QWEN_CODER_COMMAND", "Qwen worker command"),
        ("OPENHANDS_COMMAND", "OpenHands worker command"),
        ("CODEX_COMMAND", "Codex worker command"),
        ("BROWSER_QA_COMMAND", "Browser QA command"),
        ("VISUAL_REVIEW_COMMAND", "Visual review command"),
        ("QWEN_MODEL", "Qwen model"),
        ("LLM_MODEL", "OpenHands model"),
        ("LLM_BASE_URL", "OpenHands/Qwen base URL"),
        ("CODEX_MODEL", "Codex model"),
    ):
        values[key] = _prompt(label, _value(existing, key))

    enabled = _yes_no("Send observability to Langfuse", _value(existing, "SUPERVISOR_OBSERVABILITY_ENABLED") == "true")
    values["SUPERVISOR_OBSERVABILITY_ENABLED"] = "true" if enabled else "false"
    if enabled:
        values["SUPERVISOR_OBSERVABILITY_ENVIRONMENT"] = _prompt("Langfuse environment", _value(existing, "SUPERVISOR_OBSERVABILITY_ENVIRONMENT"))
        values["LANGFUSE_BASE_URL"] = _prompt("Langfuse base URL", _value(existing, "LANGFUSE_BASE_URL"))
        values["LANGFUSE_PUBLIC_KEY"] = _prompt("Langfuse public key", _value(existing, "LANGFUSE_PUBLIC_KEY"), secret=True)
        values["LANGFUSE_SECRET_KEY"] = _prompt("Langfuse secret key", _value(existing, "LANGFUSE_SECRET_KEY"), secret=True)

    _write_env(path, values)
    print(f"Wrote {path} (mode 600). Secrets were not printed.")
    print("Next: run `supervisor-run --task-id <ID>` or `supervisor-dashboard`.")


def _run(command: list[str], *, cwd: Path | None = None) -> None:
    try:
        subprocess.run(command, cwd=cwd, check=True)
    except FileNotFoundError as error:
        raise RuntimeError(f"Required command was not found: {command[0]}") from error
    except subprocess.CalledProcessError as error:
        rendered = " ".join(command)
        raise RuntimeError(f"Command failed ({error.returncode}): {rendered}") from error


def _git_output(command: list[str], *, cwd: Path) -> str:
    try:
        result = subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError) as error:
        raise RuntimeError("The Supervisor checkout is not a usable Git repository.") from error
    return result.stdout.strip()


def update_workspace(start: Path | None = None) -> Path:
    """Fast-forward the invoked Supervisor checkout and refresh its CLI tools."""

    package_root = (start or Path(__file__).resolve().parents[1]).resolve()
    repository_root = Path(_git_output(["git", "rev-parse", "--show-toplevel"], cwd=package_root))
    if _git_output(["git", "status", "--porcelain"], cwd=repository_root):
        raise RuntimeError(
            f"Refusing to update a Supervisor checkout with local changes: {repository_root}. "
            "Commit, stash, or discard those changes first."
        )
    print(f"Updating Supervisor tools in {repository_root}")
    _run(["git", "pull", "--ff-only", "origin", "main"], cwd=repository_root)
    _run([sys.executable, "-m", "pip", "install", "-e", ".[dev]"], cwd=repository_root)
    print("Supervisor tools are up to date.")
    return repository_root


def choose_python(requested: str | None = None) -> str:
    """Find a Python 3.10+ interpreter on PATH, or validate an override."""

    candidates = [requested] if requested else [
        "python3.14", "python3.13", "python3.12", "python3.11", "python3.10", "python3", "python",
    ]
    for candidate in candidates:
        if not candidate:
            continue
        resolved = shutil.which(candidate)
        if not resolved:
            continue
        probe = subprocess.run(
            [resolved, "-c", "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"],
            text=True,
            capture_output=True,
            check=False,
        )
        if probe.returncode != 0:
            continue
        try:
            major, minor = (int(part) for part in probe.stdout.strip().split(".", maxsplit=1))
        except ValueError:
            continue
        if (major, minor) >= MINIMUM_PYTHON_VERSION:
            return resolved
    if requested:
        raise RuntimeError(f"{requested!r} is not an available Python {MINIMUM_PYTHON_VERSION[0]}.{MINIMUM_PYTHON_VERSION[1]}+ interpreter.")
    raise RuntimeError("No Python 3.10+ interpreter was found on PATH. Install one or pass --python <path>.")


def _append_gitignore(path: Path, entry: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    if entry in {line.strip() for line in existing.splitlines()}:
        return
    newline = "" if not existing or existing.endswith("\n") else "\n"
    path.write_text(f"{existing}{newline}{entry}\n", encoding="utf-8")


def local_langfuse_running() -> bool:
    """Return whether the shared local Langfuse endpoint is reachable."""

    try:
        with urlopen("http://127.0.0.1:3001/", timeout=2) as response:
            return 200 <= response.status < 500
    except (OSError, URLError):
        return False


def setup_local_langfuse(
    supervisor_root: Path,
    *,
    email: str | None = None,
    name: str | None = None,
    password: str | None = None,
) -> None:
    """Start one local Langfuse instance only when a shared one is absent."""

    if local_langfuse_running():
        print("Reusing the shared local Langfuse instance at http://127.0.0.1:3001.")
        return
    script = supervisor_root / "observability" / "setup-local.sh"
    if not script.is_file():
        raise RuntimeError(f"Local Langfuse bootstrap script is missing: {script}")
    print("No local Langfuse instance is running; starting the shared local setup.")
    command = ["bash", str(script)]
    if email:
        command.extend(["--email", email])
    if name:
        command.extend(["--name", name])
    if password:
        command.extend(["--password", password])
    _run(command, cwd=supervisor_root)


def initialise_project(
    project_root: Path,
    *,
    supervisor_url: str = DEFAULT_SUPERVISOR_URL,
    python: str | None = None,
    install: bool = True,
    observability: bool = True,
    langfuse_email: str | None = None,
    langfuse_name: str | None = None,
    langfuse_password: str | None = None,
) -> None:
    """Create an empty Git project ready to run scoped supervisor runbooks."""

    project_root = project_root.expanduser().resolve()
    if project_root.exists() and any(project_root.iterdir()):
        raise ValueError(f"Project directory is not empty: {project_root}")
    project_root.mkdir(parents=True, exist_ok=True)

    print(f"Initialising Git project: {project_root}")
    _run(["git", "init"], cwd=project_root)
    print(f"Adding supervisor submodule: {supervisor_url}")
    _run(["git", "submodule", "add", supervisor_url, "supervisor"], cwd=project_root)

    runbooks = project_root / "runbooks"
    runbooks.mkdir(exist_ok=True)
    (runbooks / "README.md").write_text(RUNBOOKS_README, encoding="utf-8")
    (runbooks / "TEMPLATE.md").write_text(RUNBOOK_TEMPLATE, encoding="utf-8")
    _append_gitignore(project_root / ".gitignore", "/.state/")

    example = project_root / "supervisor" / ".env.example"
    config = project_root / "supervisor" / ".env"
    if example.is_file() and not config.exists():
        config.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")
        config.chmod(0o600)

    if install:
        venv = project_root / "supervisor" / ".venv"
        selected_python = choose_python(python)
        print(f"Creating virtual environment with {selected_python}")
        _run([selected_python, "-m", "venv", str(venv)], cwd=project_root)
        venv_python = venv / "bin" / "python"
        print("Installing supervisor dependencies")
        _run([str(venv_python), "-m", "pip", "install", "-e", ".[dev]"], cwd=project_root / "supervisor")

    if observability:
        setup_local_langfuse(
            project_root / "supervisor",
            email=langfuse_email,
            name=langfuse_name,
            password=langfuse_password,
        )

    print("Project ready.")
    print(f"1. Edit {runbooks / 'TEMPLATE.md'} and save it as your first task runbook.")
    print(f"2. Run: cd {project_root / 'supervisor'} && ./.venv/bin/supervisor configure")
    print("3. Set explicit worker commands, Langfuse project keys, and write permissions before running a task.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Configure and maintain an evidence-gated supervisor.")
    commands = parser.add_subparsers(dest="command", required=True)
    configure_parser = commands.add_parser("configure", help="Interactively create or update an ignored .env configuration file.")
    configure_parser.add_argument("--config", type=Path, default=Path(".env"), help="Configuration file to write (default: .env).")
    init_parser = commands.add_parser("init", help="Interactively create and configure an empty Git project with the supervisor, runbooks, and shared Langfuse setup.")
    init_parser.add_argument("project", type=Path, nargs="?", help="Optional new or empty project directory; prompted for when omitted.")
    init_parser.add_argument("--supervisor-url", default=DEFAULT_SUPERVISOR_URL, help="Git URL for the supervisor submodule.")
    init_parser.add_argument("--python", help="Optional Python 3.10+ interpreter override; by default the best compatible interpreter on PATH is selected.")
    init_parser.add_argument("--no-install", action="store_true", help="Create files and submodule but skip virtualenv and dependency installation.")
    init_parser.add_argument("--no-observability", action="store_true", help="Do not reuse or start the shared local Langfuse setup.")
    init_parser.add_argument("--non-interactive", action="store_true", help="Use defaults and skip all setup prompts; intended for automation.")
    commands.add_parser("update", help="Fast-forward this Supervisor checkout from origin/main and reinstall its CLI tools.")
    arguments = parser.parse_args()
    if arguments.command == "configure":
        configure(arguments.config.expanduser().resolve())
    if arguments.command == "update":
        try:
            update_workspace()
        except RuntimeError as error:
            parser.error(str(error))
    if arguments.command == "init":
        try:
            if arguments.non_interactive and arguments.project is None:
                parser.error("project is required with --non-interactive")
            project_path = (
                arguments.project.expanduser().resolve()
                if arguments.non_interactive
                else _project_path_prompt(arguments.project.expanduser().resolve() if arguments.project else None)
            )
            if project_path.exists() and any(project_path.iterdir()):
                parser.error(f"Project directory is not empty: {project_path}")
            observability = not arguments.no_observability
            bootstrap_account: dict[str, str | None] = {}
            if observability and not arguments.non_interactive and not local_langfuse_running():
                print("\nNo shared local Langfuse instance is running. Configure its initial administrator:")
                if _yes_no("Start shared local Langfuse now", True):
                    bootstrap_account = {
                        "langfuse_email": _prompt("Initial Langfuse email", "local@supervisor.invalid"),
                        "langfuse_name": _prompt("Initial Langfuse display name", "Local Operator"),
                        "langfuse_password": _prompt("Initial Langfuse password (leave blank to generate securely)", "", secret=True),
                    }
                else:
                    observability = False
            initialise_project(
                project_path,
                supervisor_url=arguments.supervisor_url,
                python=arguments.python,
                install=not arguments.no_install,
                observability=observability,
                **bootstrap_account,
            )
            if not arguments.non_interactive:
                print("\nConfigure this project's supervisor:")
                configure(project_path / "supervisor" / ".env")
        except (RuntimeError, ValueError) as error:
            parser.error(str(error))


if __name__ == "__main__":
    main()
